workspace 'Examples.xcworkspace'
platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

abstract_target 'Example' do
  pod 'ReactorKit', :path => '../'
  pod 'RxSwift', '~> 6.0'
  pod 'RxCocoa', '~> 6.0'

  target 'Counter' do
    project 'Counter/Counter.xcodeproj'
  end

  target 'GitHubSearch' do
    project 'GitHubSearch/GitHubSearch.xcodeproj'
  end
end

post_install do |installer|
    installer.generated_projects.each do |project|
          project.targets.each do |target|
              target.build_configurations.each do |config|
                  config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
               end
          end
   end
end